# Generated by Django 2.2.10 on 2022-03-13 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(choices=[('AD', 'Admin'), ('LA', 'Lawyer'), ('CU', 'Customer')], max_length=64, unique=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RolPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('permission', models.CharField(choices=[('A01', 'Admin:Access'), ('U02', 'User:CreateAdmin'), ('U03', 'User:CreateLawyer'), ('U04', 'User:CreateCustomer'), ('U05', 'User:Login')], max_length=3)),
                ('state', models.BooleanField(default=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='rols.Rol')),
            ],
            options={
                'unique_together': {('rol', 'permission')},
            },
        ),
    ]
