# Generated by Django 2.2.10 on 2022-02-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rols', '0002_auto_20220213_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='name',
            field=models.CharField(choices=[('AD', 'Admin'), ('LA', 'Lawyer'), ('CU', 'Customer')], max_length=64, unique=True),
        ),
    ]
