# Generated by Django 2.2.10 on 2022-02-23 15:40

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='country',
            field=django_countries.fields.CountryField(default=None, max_length=2),
        ),
    ]
