# Generated by Django 2.2.10 on 2022-02-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220218_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reviewd_by_admin',
            new_name='reviewed_by_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='addresss'),
        ),
        migrations.AddField(
            model_name='user',
            name='cellphone',
            field=models.CharField(blank=True, max_length=32, verbose_name='cellphone of User'),
        ),
        migrations.AddField(
            model_name='user',
            name='dni',
            field=models.CharField(blank=True, max_length=32, verbose_name='DNI of User'),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Telfone of User'),
        ),
    ]
