# Generated by Django 2.2.10 on 2022-02-18 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220218_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateTimeField(verbose_name='Fecha de Nacimiento')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('NB', 'No Binary'), ('PND', 'I prefer not to say')], max_length=4, verbose_name='Genero')),
                ('live_in', models.TextField(blank=True, null=True, verbose_name='Live in')),
                ('phone_number', models.TextField(blank=True, default='', null=True, verbose_name='Número de teléfono')),
                ('web_site', models.TextField(blank=True, default='', null=True, verbose_name='Web Site')),
                ('about_me', models.TextField(blank=True, default='', null=True, verbose_name='About Me')),
                ('country', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Pais')),
                ('language', models.CharField(blank=True, default='en', max_length=255, null=True, verbose_name='Idioma')),
                ('head_line', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Head line')),
                ('birth_date_state', models.BooleanField(default=True, verbose_name='Birth date is public.')),
                ('gender_state', models.BooleanField(default=True, verbose_name='Gender State is public.')),
                ('live_in_state', models.BooleanField(default=True, verbose_name='Live in  is public.')),
                ('phone_number_state', models.BooleanField(default=True, verbose_name='Phone is public.')),
                ('web_site_state', models.BooleanField(default=True, verbose_name='Web Site is public.')),
                ('about_me_state', models.BooleanField(default=True, verbose_name='About Me is public.')),
                ('country_state', models.BooleanField(default=True, verbose_name='Country is public.')),
                ('language_state', models.BooleanField(default=True, verbose_name='Language is public.')),
                ('head_line_state', models.BooleanField(default=True, verbose_name='Headline is public.')),
                ('email_state', models.BooleanField(default=True, verbose_name='Email is public.')),
                ('account_state', models.BooleanField(default=True, verbose_name='Account visible.')),
                ('account_public', models.BooleanField(default=True, verbose_name='Cuenta publica.')),
                ('term_of_services_accepted', models.BooleanField(default=True, verbose_name='Term of service.')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('change_password', models.BooleanField(default=False, verbose_name='Need to change Password.')),
                ('old_password', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Idioma')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ghuser')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('matricula', models.CharField(max_length=32, unique=True, verbose_name='Matricula')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
