# Generated by Django 2.2.10 on 2022-02-23 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profilepicture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dni',
            new_name='run',
        ),
        migrations.CreateModel(
            name='RUNPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_l', models.FileField(max_length=255, null=True, upload_to='x/x1', verbose_name='picture size large 1024x1024')),
                ('img_m', models.FileField(default='', max_length=255, null=True, upload_to='x/x5', verbose_name='picture size medium 400x400')),
                ('thumbnail', models.FileField(default='', max_length=255, null=True, upload_to='x/x4', verbose_name='picture size small 70x70')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('is_current_profile_picture', models.BooleanField(default=True, verbose_name='current_profile picture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='runpicture')),
            ],
            options={
                'verbose_name': 'Foto de Perfil',
                'verbose_name_plural': 'Fotos de Perfil',
            },
        ),
        migrations.CreateModel(
            name='MatriculaPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_l', models.FileField(max_length=255, null=True, upload_to='x/x1', verbose_name='picture size large 1024x1024')),
                ('img_m', models.FileField(default='', max_length=255, null=True, upload_to='x/x5', verbose_name='picture size medium 400x400')),
                ('thumbnail', models.FileField(default='', max_length=255, null=True, upload_to='x/x4', verbose_name='picture size small 70x70')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('is_current_profile_picture', models.BooleanField(default=True, verbose_name='current_profile picture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='matriculapicture')),
            ],
            options={
                'verbose_name': 'Foto de Perfil',
                'verbose_name_plural': 'Fotos de Perfil',
            },
        ),
    ]
