# Generated by Django 2.2.10 on 2022-02-23 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220223_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profilepicture', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
