# Generated by Django 2.2.10 on 2022-02-23 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220223_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='runpicture',
            options={'verbose_name': 'RUN imagen', 'verbose_name_plural': 'Run imagenes'},
        ),
        migrations.RenameField(
            model_name='matriculapicture',
            old_name='is_current_profile_picture',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='runpicture',
            old_name='is_current_profile_picture',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='matriculapicture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='matriculapictures'),
        ),
        migrations.AlterField(
            model_name='profilepicture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profilepictures', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='runpicture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='runpictures'),
        ),
        migrations.AlterField(
            model_name='user',
            name='run',
            field=models.CharField(blank=True, max_length=32, verbose_name='RUN of User'),
        ),
    ]
