# Generated by Django 2.2.10 on 2022-02-23 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220223_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculapicture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculapictures', to=settings.AUTH_USER_MODEL, verbose_name='matriculapictures'),
        ),
        migrations.AlterField(
            model_name='runpicture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runpictures', to=settings.AUTH_USER_MODEL, verbose_name='runpictures'),
        ),
    ]
