# Generated by Django 2.2.10 on 2022-02-23 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220223_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=256, verbose_name='University')),
                ('career', models.CharField(max_length=256, verbose_name='Career')),
                ('academic_degree', models.CharField(choices=[('DI', 'Diploma'), ('TE', 'Technician degree'), ('CO', 'College degree'), ('MA', "Master's degree"), ('DO', 'Doctoral degree / Doctorate'), ('PD', 'Post Doctoral degree /Post Doctorate')], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to=settings.AUTH_USER_MODEL, verbose_name='degree')),
            ],
        ),
    ]
