# Generated by Django 2.2.10 on 2022-03-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20220223_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='img_l',
            field=models.ImageField(max_length=255, null=True, upload_to='x/x1', verbose_name='picture size large 1024x1024'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='img_m',
            field=models.ImageField(default='', max_length=255, null=True, upload_to='x/x5', verbose_name='picture size medium 400x400'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='thumbnail',
            field=models.ImageField(default='', max_length=255, null=True, upload_to='x/x4', verbose_name='picture size small 70x70'),
        ),
        migrations.AlterField(
            model_name='matriculapicture',
            name='img_l',
            field=models.ImageField(max_length=255, null=True, upload_to='x/x1', verbose_name='picture size large 1024x1024'),
        ),
        migrations.AlterField(
            model_name='matriculapicture',
            name='img_m',
            field=models.ImageField(default='', max_length=255, null=True, upload_to='x/x5', verbose_name='picture size medium 400x400'),
        ),
        migrations.AlterField(
            model_name='matriculapicture',
            name='thumbnail',
            field=models.ImageField(default='', max_length=255, null=True, upload_to='x/x4', verbose_name='picture size small 70x70'),
        ),
        migrations.AlterField(
            model_name='profilepicture',
            name='img_l',
            field=models.ImageField(max_length=255, null=True, upload_to='x/x1', verbose_name='picture size large 1024x1024'),
        ),
        migrations.AlterField(
            model_name='profilepicture',
            name='img_m',
            field=models.ImageField(default='', max_length=255, null=True, upload_to='x/x5', verbose_name='picture size medium 400x400'),
        ),
        migrations.AlterField(
            model_name='profilepicture',
            name='thumbnail',
            field=models.ImageField(default='', max_length=255, null=True, upload_to='x/x4', verbose_name='picture size small 70x70'),
        ),
        migrations.AlterField(
            model_name='runpicture',
            name='img_l',
            field=models.ImageField(max_length=255, null=True, upload_to='x/x1', verbose_name='picture size large 1024x1024'),
        ),
        migrations.AlterField(
            model_name='runpicture',
            name='img_m',
            field=models.ImageField(default='', max_length=255, null=True, upload_to='x/x5', verbose_name='picture size medium 400x400'),
        ),
        migrations.AlterField(
            model_name='runpicture',
            name='thumbnail',
            field=models.ImageField(default='', max_length=255, null=True, upload_to='x/x4', verbose_name='picture size small 70x70'),
        ),
    ]
