# Generated by Django 2.2.10 on 2022-03-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20220302_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='matricula',
            field=models.CharField(blank=True, max_length=32, verbose_name='Matricula'),
        ),
    ]
