# Generated by Django 2.2.10 on 2022-03-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20220302_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reviewed_by_admin',
            field=models.CharField(choices=[('A', 'PASSED'), ('R', 'REJECTED'), ('P', 'PENDING')], max_length=2),
        ),
    ]
