# Generated by Django 2.2.10 on 2022-03-09 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_region_country'),
        ('users', '0015_auto_20220304_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='region',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regions.Region'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reviewed_by_admin',
            field=models.CharField(choices=[('A', 'PASSED'), ('R', 'REJECTED'), ('P', 'PENDING')], max_length=2, verbose_name='Reviewed by Admin'),
        ),
    ]
