# Generated by Django 2.2.10 on 2022-03-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='lawyers',
            field=models.ManyToManyField(to='users.Lawyer'),
        ),
    ]
