# Generated by Django 2.2.10 on 2022-03-10 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_area_lawyers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='lawyers',
        ),
    ]
