# Generated by Django 2.2.10 on 2022-03-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20220310_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='lawyers',
        ),
        migrations.AddField(
            model_name='lawyer',
            name='areas',
            field=models.ManyToManyField(to='users.Area'),
        ),
        migrations.DeleteModel(
            name='LawyerArea',
        ),
    ]
