# Generated by Django 2.2.10 on 2022-03-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20220310_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default='2000-01-01', verbose_name='Birth date'),
            preserve_default=False,
        ),
    ]
